name: Deploy to VPS

on:
  push:
    branches:
      - master  # Скрипт срабатывает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            source projects/test/venv/bin/activate
            cd projects/test/TestServerFeatures/

            git pull origin main
            pip install --upgrade pip
            pip install -r requirements.txt
            
            python3 app.py